### ISSUE TITLE
intervalId is not guaranteed to be cleared

### ISSUE THREAD

**Issue by jangie** [xurizaemon/hubot-pingdom-tools#3]
Recently, my teammates found that when hubot was queried for whether a URL was fast twice in quick succession, that hubot would essentially enter into a loop, polling the result and reporting back each time.

One of my teammates found that on transpilation, the coffeescript for setting the intervalId would turn to:

```
return this.intervalId = setInterval(function() {
...
```

If this.intervalId is already set and not cleared by the time the second request to hubot comes in, this.intervalId will be set to the second request's corresponding intervalId. This means that when the polling comes back successfully for the first request, that this.intervalId no longer corresponds to the first request, and thus the interval cannot be cleared.

None of us are particularly well-versed in coffeescript, but suspect that this can be solved by creating some sort of map datastructure which holds onto (e.g.) a message id and the corresponding intervalId, and clearing the interval and map entry based on the original message's id.

**Comment by xurizaemon** [comment]
hey, thanks! glad to know this is being used :D

will take a look, sorry for not spotting this until now
